export { LinenTab } from './LinenTab'
export { ConsumableTab } from './ConsumableTab'
export { ConsumableTabBooking } from './ConsumableTabBooking'
export { EquipmentTab } from './EquipmentTab'
export { FurnitureTab } from './FurnitureTab'
