// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-hotels.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.80.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Ch\u01B0a x\xE1c th\u1EF1c. H\xE3y k\u1EBFt n\u1ED1i l\u1EA1i t\xE0i kho\u1EA3n." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}
async function getUserScope(ctx) {
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.from("users").select("tenant_id, hotel_id, full_name").eq("id", ctx.getUserId()).maybeSingle();
  if (error) throw new Error(error.message);
  if (!data?.tenant_id) throw new Error("T\xE0i kho\u1EA3n ch\u01B0a g\u1EAFn v\u1EDBi \u0111\u01A1n v\u1ECB (tenant) n\xE0o.");
  return { supabase, tenantId: data.tenant_id, hotelId: data.hotel_id, fullName: data.full_name };
}

// src/lib/mcp/tools/list-hotels.ts
var list_hotels_default = defineTool({
  name: "list_hotels",
  title: "Danh s\xE1ch kh\xE1ch s\u1EA1n",
  description: "Li\u1EC7t k\xEA c\xE1c kh\xE1ch s\u1EA1n thu\u1ED9c \u0111\u01A1n v\u1ECB c\u1EE7a ng\u01B0\u1EDDi d\xF9ng \u0111ang \u0111\u0103ng nh\u1EADp.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    try {
      const { supabase, tenantId } = await getUserScope(ctx);
      const { data, error } = await supabase.from("hotels").select("id, code, name, city, status, total_rooms, total_floors").eq("tenant_id", tenantId).order("name");
      if (error) return errorResult(error.message);
      return jsonResult(data ?? []);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "L\u1ED7i kh\xF4ng x\xE1c \u0111\u1ECBnh");
    }
  }
});

// src/lib/mcp/tools/list-rooms.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";
var list_rooms_default = defineTool2({
  name: "list_rooms",
  title: "Danh s\xE1ch ph\xF2ng",
  description: "Li\u1EC7t k\xEA ph\xF2ng c\xF9ng tr\u1EA1ng th\xE1i hi\u1EC7n t\u1EA1i (tr\u1ED1ng, \u0111ang \u1EDF, c\u1EA7n d\u1ECDn, b\u1EA3o tr\xEC...). C\xF3 th\u1EC3 l\u1ECDc theo kh\xE1ch s\u1EA1n, tr\u1EA1ng th\xE1i ho\u1EB7c t\u1EA7ng.",
  inputSchema: {
    hotel_id: z.string().uuid().optional().describe("ID kh\xE1ch s\u1EA1n c\u1EA7n l\u1ECDc."),
    status: z.string().optional().describe("Tr\u1EA1ng th\xE1i ph\xF2ng c\u1EA7n l\u1ECDc, v\xED d\u1EE5 available, occupied, dirty, cleaning."),
    floor: z.number().int().optional().describe("S\u1ED1 t\u1EA7ng c\u1EA7n l\u1ECDc."),
    limit: z.number().int().min(1).max(200).default(50).describe("S\u1ED1 b\u1EA3n ghi t\u1ED1i \u0111a.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ hotel_id, status, floor, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    try {
      const { supabase, tenantId } = await getUserScope(ctx);
      let query = supabase.from("rooms").select("id, room_number, floor, room_type, status, base_price, hotel_id, notes").eq("tenant_id", tenantId).order("floor").order("room_number").limit(limit ?? 50);
      if (hotel_id) query = query.eq("hotel_id", hotel_id);
      if (status) query = query.eq("status", status);
      if (typeof floor === "number") query = query.eq("floor", floor);
      const { data, error } = await query;
      if (error) return errorResult(error.message);
      return jsonResult(data ?? []);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "L\u1ED7i kh\xF4ng x\xE1c \u0111\u1ECBnh");
    }
  }
});

// src/lib/mcp/tools/list-bookings.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_bookings_default = defineTool3({
  name: "list_bookings",
  title: "Danh s\xE1ch \u0111\u1EB7t ph\xF2ng",
  description: "Li\u1EC7t k\xEA \u0111\u1EB7t ph\xF2ng theo kho\u1EA3ng ng\xE0y nh\u1EADn ph\xF2ng, tr\u1EA1ng th\xE1i ho\u1EB7c kh\xE1ch s\u1EA1n. D\xF9ng \u0111\u1EC3 xem l\u1ECBch nh\u1EADn/tr\u1EA3 ph\xF2ng.",
  inputSchema: {
    hotel_id: z2.string().uuid().optional().describe("ID kh\xE1ch s\u1EA1n c\u1EA7n l\u1ECDc."),
    status: z2.string().optional().describe("Tr\u1EA1ng th\xE1i \u0111\u1EB7t ph\xF2ng, v\xED d\u1EE5 confirmed, checked_in, checked_out, cancelled."),
    from_date: z2.string().optional().describe("Ng\xE0y nh\u1EADn ph\xF2ng t\u1EEB (YYYY-MM-DD)."),
    to_date: z2.string().optional().describe("Ng\xE0y nh\u1EADn ph\xF2ng \u0111\u1EBFn (YYYY-MM-DD)."),
    limit: z2.number().int().min(1).max(200).default(50).describe("S\u1ED1 b\u1EA3n ghi t\u1ED1i \u0111a.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ hotel_id, status, from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    try {
      const { supabase, tenantId } = await getUserScope(ctx);
      let query = supabase.from("room_bookings").select(
        "id, booking_reference, guest_name, guest_phone, booking_type, status, payment_status, check_in_date, check_out_date, total_amount, amount_paid, deposit_amount, room_id, hotel_id"
      ).eq("tenant_id", tenantId).order("check_in_date", { ascending: false }).limit(limit ?? 50);
      if (hotel_id) query = query.eq("hotel_id", hotel_id);
      if (status) query = query.eq("status", status);
      if (from_date) query = query.gte("check_in_date", from_date);
      if (to_date) query = query.lte("check_in_date", to_date);
      const { data, error } = await query;
      if (error) return errorResult(error.message);
      return jsonResult(data ?? []);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "L\u1ED7i kh\xF4ng x\xE1c \u0111\u1ECBnh");
    }
  }
});

// src/lib/mcp/tools/list-housekeeping-tasks.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_housekeeping_tasks_default = defineTool4({
  name: "list_housekeeping_tasks",
  title: "Danh s\xE1ch c\xF4ng vi\u1EC7c bu\u1ED3ng ph\xF2ng",
  description: "Li\u1EC7t k\xEA c\xF4ng vi\u1EC7c bu\u1ED3ng ph\xF2ng (d\u1ECDn ph\xF2ng, QC, b\u1ED5 sung \u0111\u1ED3) theo tr\u1EA1ng th\xE1i, kh\xE1ch s\u1EA1n ho\u1EB7c ch\u1EC9 c\xF4ng vi\u1EC7c c\u1EE7a t\xF4i.",
  inputSchema: {
    hotel_id: z3.string().uuid().optional().describe("ID kh\xE1ch s\u1EA1n c\u1EA7n l\u1ECDc."),
    status: z3.string().optional().describe("Tr\u1EA1ng th\xE1i c\xF4ng vi\u1EC7c, v\xED d\u1EE5 pending, in_progress, awaiting_review, completed."),
    only_mine: z3.boolean().default(false).describe("Ch\u1EC9 l\u1EA5y c\xF4ng vi\u1EC7c \u0111\u01B0\u1EE3c giao cho t\xF4i."),
    limit: z3.number().int().min(1).max(200).default(50).describe("S\u1ED1 b\u1EA3n ghi t\u1ED1i \u0111a.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ hotel_id, status, only_mine, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    try {
      const { supabase, tenantId } = await getUserScope(ctx);
      let query = supabase.from("housekeeping_tasks").select(
        "id, title, task_type, status, priority, qc_status, qc_required, room_id, hotel_id, assigned_to, due_at, created_at, completed_at"
      ).eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(limit ?? 50);
      if (hotel_id) query = query.eq("hotel_id", hotel_id);
      if (status) query = query.eq("status", status);
      if (only_mine) query = query.eq("assigned_to", ctx.getUserId());
      const { data, error } = await query;
      if (error) return errorResult(error.message);
      return jsonResult(data ?? []);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "L\u1ED7i kh\xF4ng x\xE1c \u0111\u1ECBnh");
    }
  }
});

// src/lib/mcp/tools/create-maintenance-request.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var create_maintenance_request_default = defineTool5({
  name: "create_maintenance_request",
  title: "T\u1EA1o y\xEAu c\u1EA7u b\u1EA3o tr\xEC",
  description: "T\u1EA1o m\u1ED9t y\xEAu c\u1EA7u b\u1EA3o tr\xEC m\u1EDBi cho kh\xE1ch s\u1EA1n c\u1EE7a ng\u01B0\u1EDDi d\xF9ng. Ch\u1EC9 t\u1EA1o khi ng\u01B0\u1EDDi d\xF9ng y\xEAu c\u1EA7u r\xF5 r\xE0ng.",
  inputSchema: {
    title: z4.string().trim().min(3).describe("Ti\xEAu \u0111\u1EC1 ng\u1EAFn g\u1ECDn c\u1EE7a s\u1EF1 c\u1ED1."),
    description: z4.string().trim().min(3).describe("M\xF4 t\u1EA3 chi ti\u1EBFt s\u1EF1 c\u1ED1."),
    location: z4.string().trim().min(1).describe("V\u1ECB tr\xED x\u1EA3y ra s\u1EF1 c\u1ED1, v\xED d\u1EE5 'Ph\xF2ng 201' ho\u1EB7c 'S\u1EA3nh t\u1EA7ng 1'."),
    issue_type: z4.enum(["repair", "replace", "inspection", "cleaning", "other"]).default("repair").describe("Lo\u1EA1i s\u1EF1 c\u1ED1."),
    priority: z4.enum(["low", "medium", "high", "urgent"]).default("medium").describe("M\u1EE9c \u01B0u ti\xEAn."),
    hotel_id: z4.string().uuid().optional().describe("ID kh\xE1ch s\u1EA1n; m\u1EB7c \u0111\u1ECBnh l\u1EA5y kh\xE1ch s\u1EA1n c\u1EE7a ng\u01B0\u1EDDi d\xF9ng."),
    room_id: z4.string().uuid().optional().describe("ID ph\xF2ng li\xEAn quan (n\u1EBFu c\xF3).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    try {
      const { supabase, tenantId, hotelId } = await getUserScope(ctx);
      const targetHotel = input.hotel_id ?? hotelId;
      if (!targetHotel) return errorResult("Kh\xF4ng x\xE1c \u0111\u1ECBnh \u0111\u01B0\u1EE3c kh\xE1ch s\u1EA1n. H\xE3y truy\u1EC1n hotel_id.");
      const requestCode = `MR-${Date.now().toString(36).toUpperCase()}`;
      const { data, error } = await supabase.from("maintenance_requests").insert({
        tenant_id: tenantId,
        hotel_id: targetHotel,
        room_id: input.room_id ?? null,
        request_code: requestCode,
        title: input.title,
        description: input.description,
        location: input.location,
        issue_type: input.issue_type,
        priority: input.priority,
        reported_by: ctx.getUserId()
      }).select("id, request_code, title, status, priority, created_at").maybeSingle();
      if (error) return errorResult(error.message);
      return jsonResult(data);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : "L\u1ED7i kh\xF4ng x\xE1c \u0111\u1ECBnh");
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "ehjtoajnlnuvuiwkpmbp";
var mcp_default = defineMcp({
  name: "hotel-inventory-hub",
  title: "Hotel Inventory Hub",
  version: "0.1.0",
  instructions: "C\xF4ng c\u1EE5 v\u1EADn h\xE0nh kh\xE1ch s\u1EA1n RoomQc. D\xF9ng list_hotels/list_rooms \u0111\u1EC3 xem t\xECnh tr\u1EA1ng ph\xF2ng, list_bookings \u0111\u1EC3 xem \u0111\u1EB7t ph\xF2ng, list_housekeeping_tasks \u0111\u1EC3 xem c\xF4ng vi\u1EC7c bu\u1ED3ng ph\xF2ng, create_maintenance_request \u0111\u1EC3 t\u1EA1o y\xEAu c\u1EA7u b\u1EA3o tr\xEC. M\u1ECDi d\u1EEF li\u1EC7u \u0111\u1EC1u gi\u1EDBi h\u1EA1n theo t\xE0i kho\u1EA3n \u0111\xE3 \u0111\u0103ng nh\u1EADp.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_hotels_default, list_rooms_default, list_bookings_default, list_housekeeping_tasks_default, create_maintenance_request_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
